import React from "react";
import Link from "next/link";
import Image from "next/image";
import { Eye, Heart } from "react-ionicons";
import { BlogsType } from "../types/supabase";
import dayjs from "dayjs";
import logoRoundedSvg from "../public/logo-rounded.svg";
import type { SponsorsResponse } from "../utils/apolloClient";

const formatDate = (date: string | number | Date) =>
  dayjs(new Date(date)).format("dddd, MMMM D, YYYY");

// Generated by GitHub Copilot 💚
// A function to calculate read time based on how many characters there are.
const calculateReadTime = (content: string) => {
  const words = content.split(" ").length;
  const minutes = Math.ceil(words / 200);
  return minutes;
};

const Footer = ({
  blogData,
  sponsorsData,
}: {
  blogData: BlogsType | null;
  sponsorsData: SponsorsResponse | null;
}) => {
  return (
    <div>
      <div className="h-20" />

      <footer className="footer bg-secondary-content p-10 text-base-content">
        <div className="w-full">
          <div className="h-14 w-14">
            <Image src={logoRoundedSvg} alt="GodderE2D's Profile Picture" />
          </div>

          <h2 className="text-2xl">
            <strong>GodderE2D</strong>
          </h2>

          <p>A very mysterious person...</p>

          <a
            href="https://github.com/GodderE2D/godder.xyz"
            className="footer-github-link"
            title="Go to Website GitHub"
            target="_blank"
            rel="noreferrer"
          ></a>
          {sponsorsData ? (
            <>
              <div className="my-2 h-px w-full bg-base-200" />
              <div className="w-full rounded-lg bg-pink-200 p-3">
                <div className="mb-2 font-bold">
                  <a
                    className="link link-hover"
                    href="https://github.com/sponsors/GodderE2D"
                    target="_blank"
                    rel="noopener noreferrer"
                  >
                    💚 Thank you to my generous sponsors:
                  </a>
                </div>
                <div>
                  {sponsorsData.user.sponsors.edges.map(({ node: sponsor }) => (
                    <div className="flex max-h-fit max-w-fit" key={sponsor.id}>
                      <img
                        className="h-8 w-8 rounded-full"
                        src={sponsor.avatarUrl}
                        alt={`${sponsor.login}'s GitHub avatar`}
                      />
                      <div className="ml-2 self-center">
                        <a
                          href={sponsor.url}
                          target="_blank"
                          rel="noopener noreferrer"
                        >
                          <div className="link link-hover text-sm font-semibold">
                            {sponsor.login}
                          </div>
                        </a>
                        <div className="text-xs opacity-80">{sponsor.name}</div>
                        <div className="text-xs opacity-80">
                          Sponsoring since{" "}
                          {dayjs(
                            sponsor.sponsorshipsAsSponsor.nodes.find(
                              (s) =>
                                s.sponsorable.login ===
                                process.env.NEXT_PUBLIC_GITHUB_USERNAME
                            )?.createdAt
                          ).format("MMM D, YYYY")}
                        </div>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            </>
          ) : (
            ""
          )}
        </div>
        <div>
          <span className="footer-title">Pages</span>

          <div className="link link-hover">
            <Link href="/">Home</Link>
          </div>

          <div className="link link-hover">
            <Link href="/resources">Resources</Link>
          </div>

          <div className="link link-hover">
            <a
              href="https://dsc.bio/godder"
              target="_blank"
              rel="noopener noreferrer"
            >
              Bio
            </a>
          </div>

          <div className="link link-hover">
            <Link href="/blog">Blog</Link>
          </div>
        </div>
        <div>
          <span className="footer-title">Latest Blog Post</span>

          {!blogData ? (
            <p>An unknown error occurred when fetching the latest blog.</p>
          ) : (
            <div className="max-w-4xl" key={blogData.slug}>
              <Link href={`/blog/${blogData.slug}`} passHref>
                <div className="card rounded-box grid cursor-pointer bg-base-200">
                  <div className="mx-6 my-6">
                    {blogData.tags.map((tag: string) => (
                      <div key={tag} className="badge badge-success mr-2">
                        {tag}
                      </div>
                    ))}

                    <div className="h-2" />

                    <h3 className="text-2xl">
                      <strong>{blogData.title}</strong>
                    </h3>

                    <p>{blogData.description}</p>

                    <small className="opacity-60">
                      Created on {formatDate(blogData.createdAt)}{" "}
                      {blogData.updatedAt === blogData.createdAt ||
                        `• Updated on ${formatDate(blogData.updatedAt)}`}{" "}
                      • {calculateReadTime(blogData.content)} minute
                      {calculateReadTime(blogData.content) !== 1 && "s"} read
                    </small>
                  </div>
                </div>
              </Link>
            </div>
          )}
        </div>
      </footer>
    </div>
  );
};

export default Footer;
