import React from "react";
import Link from "next/link";
import type { NextPage, GetServerSideProps } from "next";
import Head from "next/head";
import Navbar from "../../components/Navbar";
import Footer from "../../components/Footer";
import dayjs from "dayjs";
import { supabase } from "../../utils/supabaseClient";
import { BlogsType } from "../../types/supabase";
import toast from "react-hot-toast";

const formatDate = (date: string | number | Date) =>
  dayjs(new Date(date)).format("dddd, MMMM D, YYYY");

// Generated by GitHub Copilot 💚
// A function to calculate read time based on how many characters there are.
const calculateReadTime = (content: string) => {
  const words = content.split(" ").length;
  const minutes = Math.ceil(words / 200);
  return minutes;
};

export const getServerSideProps: GetServerSideProps<{
  rawBlogsData: BlogsType[];
}> = async () => {
  const { data, error } = await supabase
    .from<BlogsType>("blogs")
    .select()
    .limit(10)
    .order("createdAt", { ascending: false });

  if (error) throw error;

  return {
    props: {
      rawBlogsData: data || [],
    },
  };
};

const Blog: NextPage<{ rawBlogsData: BlogsType[] }> = ({ rawBlogsData }) => {
  const [blogsData, setBlogsData] = React.useState(rawBlogsData);

  return (
    <div>
      <Head>
        <title>Blog · GodderE2D</title>
        <link rel="icon" href="/logo-rounded.png" />

        <meta property="og:title" content="Blog · GodderE2D" />
        <meta property="og:type" content="website" />
        <meta property="og:image" content="/logo-rounded.png" />
        <meta name="theme-color" content="#40bf6c" />
        <meta
          name="description"
          content="Sometimes I post here for some reason, and no ones sees it. That's sad..."
        />
        <meta
          property="og:description"
          content="Sometimes I post here for some reason, and no ones sees it. That's sad..."
        />
        <meta itemProp="name" content="Blog · GodderE2D" />
        <meta
          itemProp="description"
          content="Sometimes I post here for some reason, and no ones sees it. That's sad..."
        />
        <meta itemProp="thumbnailUrl" content="/logo-rounded.png" />
        <meta itemProp="image" content="/logo-rounded.png" />
        <meta itemProp="imageUrl" content="/logo-rounded.png" />
      </Head>

      <Navbar />

      <div className="mx-4 md:mx-12 lg:mx-36">
        <div className="mx-4 text-left">
          <h1 className="mb-5 text-5xl font-extrabold">Blog</h1>

          <p className="max-w-xl">
            Sometimes I post here for some reason, and no ones sees it. That
            {"'"}s sad...
          </p>

          <div className="h-2" />

          <p className="max-w-xl">
            Note: Blogs are currently a work-in progress.
          </p>
        </div>

        <div className="h-14" />

        <div>
          <div className="flex w-full flex-col">
            {blogsData.map((blog: BlogsType) => (
              <div key={blog.slug}>
                <Link href={`/blog/${blog.slug}`} passHref>
                  <div className="card rounded-box grid cursor-pointer bg-base-300">
                    <div className="mx-6 my-6">
                      {blog.tags.map((tag: string) => (
                        <div key={tag} className="badge badge-success mr-2">
                          {tag}
                        </div>
                      ))}

                      <div className="h-2" />

                      <h3 className="text-2xl">
                        <strong>{blog.title}</strong>
                      </h3>

                      <p>{blog.description}</p>

                      <small className="opacity-60">
                        Created on {formatDate(blog.createdAt)}{" "}
                        {blog.updatedAt === blog.createdAt ||
                          `• Updated on ${formatDate(blog.updatedAt)}`}{" "}
                        • {calculateReadTime(blog.content)} minute
                        {calculateReadTime(blog.content) !== 1 && "s"} read
                      </small>
                    </div>
                  </div>
                </Link>
                <div className="h-4" />
              </div>
            ))}

            <small
              className="link opacity-60"
              onClick={async () => {
                toast.success("Loading more blogs...");

                const { data, error } = await supabase
                  .from<BlogsType>("blogs")
                  .select()
                  .order("createdAt", { ascending: false })
                  .range(blogsData.length, blogsData.length + 10)
                  .limit(10);

                if (error) {
                  console.error(error);
                  return toast.error(
                    "An unexpected error occurred when fetching blogs. Refer to the console for details."
                  );
                }

                if (!data?.length)
                  return toast.error("You've reached the end.");

                const newBlogsData = blogsData.concat(data);
                setBlogsData(newBlogsData);

                toast.success("More blogs! Yum!");
              }}
            >
              Load more...
            </small>
          </div>
        </div>
      </div>

      <Footer blogData={blogsData[0]} />
    </div>
  );
};

export default Blog;
